# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

- name:     This playbook will install postgresql on each nodes
  hosts:    nodes

  vars_files:
    - vars/default-settings.yaml
    - group_vars/kvm_guest/cloud_images.yaml
    - group_vars/kvm_guest/postgresql_server_packages.yaml
    
  tasks:

    - block:
        - name: Loading CentOS 7 cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-7.yaml
            name:        c7x
        - name: Loading CentOS 8 Stream cluster samples
          include_vars:
            file:        vars/testlab_samples/centos-8-stream.yaml
            name:        c8s
        - name: Loading Ubuntu 20.04 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.04.yaml
            name:        u2004
        - name: Loading Ubuntu 20.10 cluster samples
          include_vars:
            file:        vars/testlab_samples/ubuntu-20.10.yaml
            name:        u2010
        - name: Loading Your custom cluster definition
          include_vars:
            file:        vars/clusters.yaml
            name:        custo
        - name: Merging all cluster definitions
          set_fact:
            clusters: "{{ custo | combine(c7x, recursive=True) | combine(c8s, recursive=True) | combine(u2004, recursive=True) | combine(u2010, recursive=True) }}"

    - name:  PostgreSQL setup -- Current provisioning facts of the VMs 
      debug:
        var: ansible_local['homelab-postgresql-provider']

    - name: PostgreSQL setup -- Computing instance directory
      set_fact:
        instance_dir: "instances/{{ lookup('file', '/var/lib/dbus/machine-id') }}"
        
    - name:  PostgreSQL setup -- Configure nodes
      block:

        - name: PostgreSQL setup -- Processing Red-Hat like VM
          block:
            - name: PostgreSQL setup -- Applying yum repo package
              yum:
                name:   "{{ postgresql_server_packages[clusters.definition[cluster_name].guest_os].yum_repo }}"
                state:  "present"
              when:     postgresql_server_packages[clusters.definition[cluster_name].guest_os].yum_repo is defined
              become:   true

            - name: PostgreSQL setup -- Applying post repo command
              shell:
                cmd:    "{{ postgresql_server_packages[clusters.definition[cluster_name].guest_os].cmd_repo }}"
                warn:   false
              when:     postgresql_server_packages[clusters.definition[cluster_name].guest_os].cmd_repo is defined
              become:   true

            - name: PostgreSQL setup -- Applying yum package
              yum:
                name:   "{{ item.name }}"
                state:  "{{ item.state }}"
              loop:     "{{  postgresql_server_packages[clusters.definition[cluster_name].guest_os].yum_list }}"
              register: result
              until:    result is succeeded
              when:     postgresql_server_packages[clusters.definition[cluster_name].guest_os].yum_list is defined
              become:   true

          when: cloud_images[clusters.definition[cluster_name].guest_os].package_manager == 'yum'

        - name: PostgreSQL setup -- Processing Debian like VM 
          block:
            - name: PostgreSQL setup -- Applying apt package
              apt:
                name:   "{{ item.name }}"
                state:  "{{ item.state }}"
              loop:     "{{  postgresql_server_packages[clusters.definition[cluster_name].guest_os].apt_list }}"
              register: result
              until:    result is succeeded
              when:     postgresql_server_packages[clusters.definition[cluster_name].guest_os].apt_list is defined
              become:   true

          when: cloud_images[clusters.definition[cluster_name].guest_os].package_manager == 'apt'

        - name: PostgreSQL setup -- Configuring Firewalld
          block:

            #
            # https://github.com/ansible/ansible/issues/71528 => using shell command :-S
            #
            #   - name: PostgreSQL setup -- Enable and start firewalld daemon
            #     systemd:
            #       name:          firewalld
            #       state:         started
            #       enabled:       yes
            #     become:          true
            #
        
            - name: PostgreSQL setup -- Enable firewalld daemon
              command:         systemctl enable firewalld
              become:          true
    
            - name: PostgreSQL setup -- Start firewalld daemon
              command:         systemctl start firewalld
              become:          true
    
            - name: PostgreSQL setup -- Firewalld - Adding network interface to the internal zone
              firewalld:
                zone:              public
                interface:         "{{ ansible_default_ipv4.interface  }}"
                permanent:         true
                state:             enabled

            - name: PostgreSQL setup -- Firewalld - Allowing postgresql port
              firewalld:
                zone:             public
                state:            enabled
                permanent:        true
                port:             5432/tcp
            
            - name: PostgreSQL setup -- Relaunching Firewalld as zone has been created
              command:         systemctl restart firewalld
              become:          true
    

          become:   true
          when: cloud_images[clusters.definition[cluster_name].guest_os].application_firewall == 'firewalld'

        - name: PostgreSQL setup -- Configuring Ufw
          block:
            - name: PostgreSQL setup -- Activating ufw as allowing by default
              ufw:
                state:             enabled
                policy:            allow

            - name: PostgreSQL setup -- Ufw - Allowing SSH
              ufw:
                rule:              allow
                name:              OpenSSH
                interface:         "{{ ansible_default_ipv4.interface  }}"
                direction:         in

            - name: PostgreSQL setup -- Ufw - Allowing postgresql port
              ufw:
                rule:              allow
                port:              '5432'
                proto:             tcp
                interface:         "{{ ansible_default_ipv4.interface  }}"
                direction:         in

            - name: PostgreSQL setup -- Activating ufw as rejecting by default
              ufw:
                state:             enabled
                policy:            reject

          become:   true
          when: cloud_images[clusters.definition[cluster_name].guest_os].application_firewall == 'ufw'


        - name: PostgreSQL setup -- reload systemd configuration
          command:         systemctl daemon-reload
          become:          true
    
        - name: Patroni setup -- Enable postgresql deamon under CentOS
          command:         systemctl enable postgresql-12
          when:            ansible_distribution == 'CentOS' 
          become:          true
    
        - name: Patroni setup -- Enable postgresql deamon under Ubuntu
          command:         systemctl enable postgresql
          when:            ansible_distribution == 'Ubuntu' 
          become:          true
    
        - name: PostgreSQL setup -- stopping postgresql daemon until HA has not yet been configured under CentOS
          command:         systemctl stop postgresql-12
          when:            ansible_distribution == 'CentOS' 
          become:          true

        - name: PostgreSQL setup -- stopping postgresql daemon until HA has not yet been configured under Ubuntu
          command:         systemctl stop postgresql
          when:            ansible_distribution == 'Ubuntu' 
          become:          true

        - name: PostgreSQL setup -- Storing new state inside the homelab-postgresql-provider custom fact
          lineinfile:
            path:   /etc/ansible/facts.d/homelab-postgresql-provider.fact
            line:   "postgresql=true"
          become:   true

        - name: PostgreSQL setup -- Reload the homelab-postgresql-provider custom fact
          setup:
            filter: ansible_local          

      when: 
        - ansible_local['homelab-postgresql-provider']['setup']['postgresql'] is not defined
