# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

cloud_images:
  "Ubuntu 20.04":
    application_security:       apparmor
    application_firewall:       ufw
    package_manager:            apt
    package_reboot_check:       reboot_required
    cloud_init_file:            cloud_init_ubuntu.cfg
    haproxy_extra_arg_file:     /etc/default/haproxy
    image_name:                 Ubuntu-20.04-CloudImage
    url:                        https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img

  "Ubuntu 20.10":
    application_security:       apparmor
    application_firewall:       ufw
    package_manager:            apt
    package_reboot_check:       reboot_required
    cloud_init_file:            cloud_init_ubuntu.cfg
    haproxy_extra_arg_file:     /etc/default/haproxy
    image_name:                 Ubuntu-20.10-CloudImage
    url:                        https://cloud-images.ubuntu.com/releases/groovy/release/ubuntu-20.10-server-cloudimg-amd64.img

  "CentOS 7":
    application_security:       selinux
    application_firewall:       firewalld
    package_manager:            yum
    package_reboot_check:       needs_restarting
    cloud_init_file:            cloud_init_centos.cfg
    haproxy_extra_arg_file:     /etc/sysconfig/haproxy
    image_name:                 CentOS-7-GenericCloud
    url:                        https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2

  "CentOS 8 Stream":
    application_security:       selinux
    application_firewall:       firewalld
    package_manager:            yum
    package_reboot_check:       needs_restarting
    cloud_init_file:            cloud_init_centos.cfg
    haproxy_extra_arg_file:     /etc/sysconfig/haproxy
    image_name:                 CentOS-8-Stream-GenericCloud
    url:                        https://cloud.centos.org/centos/8-stream/x86_64/images/CentOS-Stream-GenericCloud-8-20201217.0.x86_64.qcow2
