# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

etcd_packages:
  "Ubuntu 20.04":
    configuration_file: /etc/default/etcd
    apt_list:
      - { state: "present", name: "etcd"                    }  

  "Ubuntu 20.10":
    configuration_file: /etc/default/etcd
    apt_list:
      - { state: "present", name: "etcd"                    }  

  "CentOS 7":
    configuration_file: /etc/etcd/etcd.conf
    yum_list:
      - { state: "present", name: "etcd"                    }  

  "CentOS 8 Stream":
    configuration_file: /etc/etcd/etcd.conf
    yum_list:
      - { state: "present", name: "http://mirror.centos.org/centos/7/extras/x86_64/Packages/etcd-3.2.28-1.el7_8.x86_64.rpm" }  

