# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

postgresql_server_packages:
  "Ubuntu 20.04":
    apt_list:
      - { state: "present", name: "postgresql"              }  
      - { state: "present", name: "postgresql-common"       }  
      - { state: "present", name: "python3-psycopg2"        }  

  "Ubuntu 20.10":
    apt_list:
      - { state: "present", name: "postgresql"              }  
      - { state: "present", name: "postgresql-common"       }  
      - { state: "present", name: "python3-psycopg2"        }  

  "CentOS 7":
    yum_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm" 
    cmd_repo: "yum-config-manager --enable pgdg12"
    yum_list:
      - { state: "present", name: "postgresql12"            }  
      - { state: "present", name: "postgresql12-server"     }  
      - { state: "present", name: "python3-psycopg2"        }  

  "CentOS 8 Stream":
    yum_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm" 
    cmd_repo: "dnf -qy module disable postgresql"
    yum_list:
      - { state: "present", name: "postgresql12"            }  
      - { state: "present", name: "postgresql12-server"     }  
      - { state: "present", name: "python3-psycopg2"        }  

