# ------------------------------------------------------------------------------------------ #
#                                                                                            #
#                Copyright (c) 2021 - Gilles Freart. All right reserved                      #
#                                                                                            #
#  Licensed under the MIT License. See LICENSE in the project root for license information.  #
#                                                                                            #
# ------------------------------------------------------------------------------------------ #

prerequisite_packages:
  "Ubuntu 20.04":
    apt_list:
      - { state: "present", name: "mc"                      }  
      - { state: "present", name: "sed"                     }  
      - { state: "present", name: "vim"                     }  
      - { state: "present", name: "git"                     }  
      - { state: "present", name: "htop"                    }  
      - { state: "present", name: "curl"                    }  
      - { state: "present", name: "telnet"                  }  
      - { state: "present", name: "bash-completion"         }  
      - { state: "present", name: "inetutils-traceroute"    }

  "Ubuntu 20.10":
    apt_list:
      - { state: "present", name: "mc"                      }  
      - { state: "present", name: "sed"                     }  
      - { state: "present", name: "vim"                     }  
      - { state: "present", name: "git"                     }  
      - { state: "present", name: "htop"                    }  
      - { state: "present", name: "curl"                    }  
      - { state: "present", name: "telnet"                  }  
      - { state: "present", name: "bash-completion"         }  
      - { state: "present", name: "inetutils-traceroute"    }


  "CentOS 7":
    yum_list:
      - { state: "present", name: "epel-release"            }  
      - { state: "present", name: "mc"                      }  
      - { state: "present", name: "sed"                     }  
      - { state: "present", name: "vim"                     }  
      - { state: "present", name: "git"                     }  
      - { state: "present", name: "htop"                    }  
      - { state: "present", name: "curl"                    }  
      - { state: "present", name: "telnet"                  }  
      - { state: "present", name: "yum-utils"               }  
      - { state: "present", name: "bash-completion"         }  
      - { state: "absent",  name: "buildah"                 }  
      - { state: "absent",  name: "skopeo"                  }  
      - { state: "absent",  name: "podman"                  }  
      - { state: "absent",  name: "containers-common"       }  
      - { state: "absent",  name: "docker"                  }
      - { state: "absent",  name: "docker-client"           }
      - { state: "absent",  name: "docker-client-latest"    }
      - { state: "absent",  name: "docker-common"           }
      - { state: "absent",  name: "docker-latest"           }
      - { state: "absent",  name: "docker-latest-logrotate" }
      - { state: "absent",  name: "docker-logrotate"        }
      - { state: "absent",  name: "docker-engine"           }

  "CentOS 8 Stream":
    yum_list:
      - { state: "present", name: "epel-release"            }  
      - { state: "present", name: "mc"                      }  
      - { state: "present", name: "sed"                     }  
      - { state: "present", name: "vim"                     }  
      - { state: "present", name: "git"                     }  
      - { state: "present", name: "htop"                    }  
      - { state: "present", name: "curl"                    }  
      - { state: "present", name: "telnet"                  }  
      - { state: "present", name: "yum-utils"               }  
      - { state: "present", name: "bash-completion"         }  
      - { state: "absent",  name: "buildah"                 }  
      - { state: "absent",  name: "skopeo"                  }  
      - { state: "absent",  name: "podman"                  }  
      - { state: "absent",  name: "containers-common"       }  
      - { state: "absent",  name: "docker"                  }
      - { state: "absent",  name: "docker-client"           }
      - { state: "absent",  name: "docker-client-latest"    }
      - { state: "absent",  name: "docker-common"           }
      - { state: "absent",  name: "docker-latest"           }
      - { state: "absent",  name: "docker-latest-logrotate" }
      - { state: "absent",  name: "docker-logrotate"        }
      - { state: "absent",  name: "docker-engine"           }

